version: '3.7'

services:
  eventstore.db:
    container_name: eventstore-${STACK_POSTFIX}
    image: eventstore/eventstore:21.10.9-buster-slim
    restart: unless-stopped
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=${STACK_EVENTSTORE_TCP_PORT}
      - EVENTSTORE_HTTP_PORT=${STACK_EVENTSTORE_HTTP_PORT}
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - '${STACK_EVENTSTORE_TCP_PORT}:${STACK_EVENTSTORE_TCP_PORT}'
      - '${STACK_EVENTSTORE_HTTP_PORT}:${STACK_EVENTSTORE_HTTP_PORT}'
  ttsm:
    container_name: ttsm-${STACK_POSTFIX}
    restart: unless-stopped
    depends_on:
      - eventstore.db
    build:
      context: ./ttsm
      dockerfile: Dockerfile
    environment:
      - CONSISTENCY_STRATEGY
      - CONSISTENCY_P2P_PEER_URLS
      - CONSISTENCY_EVM_PEER_URLS
      - CONSISTENCY_EVM_PROVIDER
      - CONSISTENCY_EVM_CONTRACT_ADDRESS
      - CONSISTENCY_EVM_CLIENT_ADDRESS
      - PERSISTENCE_SERVICE_URL
      - PERSISTENCE_ORBITDB_ID
      - PERSISTENCE_ORBITDB_IPFS_PORT
      - PERSISTENCE_ORBITDB_IPFS_PORT_WS
      - RULES_SERVICE_URL
      - INTEGRATIONS_ZEEBE_ADDRESS
      - INTEGRATIONS_ZEEBE_AUTHORIZATION_SERVER_URL
      - INTEGRATIONS_ZEEBE_AUDIENCE
      - INTEGRATIONS_ZEEBE_CLIENT_ID
      - INTEGRATIONS_ZEEBE_CLIENT_SECRET
      - CONSISTENCY_EVM_SIGNER_PRIVATE_KEY
    ports:
      - '${STACK_TTSM_PORT}:3000'
      - '${PERSISTENCE_ORBITDB_IPFS_PORT}'
      - '${PERSISTENCE_ORBITDB_IPFS_PORT_WS}'