/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface StateTransitionMessage
 */
export interface StateTransitionMessage {
    /**
     * 
     * @type {string}
     * @memberof StateTransitionMessage
     */
    sender?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof StateTransitionMessage
     */
    signers?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof StateTransitionMessage
     */
    content?: { [key: string]: any; };
}
